# Match Data Cleaning
### Extracting Data from CSV

In [1]:
import pandas as pd

In [24]:
df = pd.read_csv("match_stats.csv", index_col=False)

In [27]:
df

,Wk,Day,Date,Time,Home,xG,Score,xG.1,Away,Attendance,Venue,Referee,Match Report,Notes
0,1.0,Fri,2023-08-11,20:00,Burnley,0.3,0–3,1.9,Manchester City,21572.0,Turf Moor,Craig Pawson,Match Report,NaN
1,1.0,Sat,2023-08-12,12:30,Arsenal,0.8,2–1,1.2,Nott'ham Forest,59984.0,Emirates Stadium,Michael Oliver,Match Report,NaN
2,1.0,Sat,2023-08-12,15:00,Everton,2.7,0–1,1.5,Fulham,39940.0,Goodison Park,Stuart Attwell,Match Report,NaN
3,1.0,Sat,2023-08-12,15:00,Brighton,4.0,4–1,1.5,Luton Town,31872.0,The American Express Community Stadium,David Coote,Match Report,NaN
4,1.0,Sat,2023-08-12,15:00,Sheffield Utd,0.5,0–1,1.9,Crystal Palace,31194.0,Bramall Lane,John Brooks,Match Report,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
418,38.0,Sun,2024-05-19,16:00,Brighton,1.7,0–2,1.3,Manchester Utd,31662.0,The American Express Community Stadium,Craig Pawson,Match Report,NaN
419,38.0,Sun,2024-05-19,16:00,Brentford,1.1,2–4,3.4,Newcastle Utd,17124.0,Gtech Community Stadium,Simon Hooper,Match Report,NaN
420,38.0,Sun,2024-05-19,16:00,Manchester City,1.9,3–1,0.4,West Ham,55097.0,Etihad Stadium,John Brooks,Match Report,NaN
421,38.0,Sun,2024-05-19,16:00,Arsenal,2.9,2–1,0.6,Everton,60312.0,Emirates Stadium,Michael Oliver,Match Report,NaN
422,38.0,Sun,2024-05-19,16:00,Sheffield Utd,1.0,0–3,3.1,Tottenham,29116.0,Bramall Lane,Andy Madley,Match Report,NaN

### Adding column to add info about the match result, based on who won, home won, away won, or tie.

In [4]:
df["Score"]

0      0–3
1      2–1
2      0–1
3      4–1
4      0–1
      ...
418    0–2
419    2–4
420    3–1
421    2–1
422    0–3
Name: Score, Length: 423, dtype: object

In [69]:
#Erasing empty rows based on score
match_result = pd.Series()
for index, row in df.iterrows():
    score = row["Score"]
    if isinstance(score,float):
        df = df.drop(index)
        continue

    #score is divided by an en dash
    result = score.split('–')
    if result[0] > result[1]:
        match_result[index] = 'H'
    elif result[0] < result[1]:
        match_result[index] = 'A'
    else:
        match_result[index] = 'T'

In [66]:
df['Result'] = match_result

In [42]:
df = df.reset_index(drop=True)

In [47]:
df = df.drop(columns=["Notes", "Match Report"])

## Result Column
**The result column will show one of three characters**
- A: The away team won
- H: The home team won
- T: The match was a tie

In [67]:
df

,Wk,Day,Date,Time,Home,xG,Score,xG.1,Away,Attendance,Venue,Referee,Result
0,1.0,Fri,2023-08-11,20:00,Burnley,0.3,0–3,1.9,Manchester City,21572.0,Turf Moor,Craig Pawson,A
1,1.0,Sat,2023-08-12,12:30,Arsenal,0.8,2–1,1.2,Nott'ham Forest,59984.0,Emirates Stadium,Michael Oliver,H
2,1.0,Sat,2023-08-12,15:00,Everton,2.7,0–1,1.5,Fulham,39940.0,Goodison Park,Stuart Attwell,A
3,1.0,Sat,2023-08-12,15:00,Brighton,4.0,4–1,1.5,Luton Town,31872.0,The American Express Community Stadium,David Coote,H
4,1.0,Sat,2023-08-12,15:00,Sheffield Utd,0.5,0–1,1.9,Crystal Palace,31194.0,Bramall Lane,John Brooks,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,38.0,Sun,2024-05-19,16:00,Brighton,1.7,0–2,1.3,Manchester Utd,31662.0,The American Express Community Stadium,Craig Pawson,A
376,38.0,Sun,2024-05-19,16:00,Brentford,1.1,2–4,3.4,Newcastle Utd,17124.0,Gtech Community Stadium,Simon Hooper,A
377,38.0,Sun,2024-05-19,16:00,Manchester City,1.9,3–1,0.4,West Ham,55097.0,Etihad Stadium,John Brooks,H
378,38.0,Sun,2024-05-19,16:00,Arsenal,2.9,2–1,0.6,Everton,60312.0,Emirates Stadium,Michael Oliver,H
379,38.0,Sun,2024-05-19,16:00,Sheffield Utd,1.0,0–3,3.1,Tottenham,29116.0,Bramall Lane,Andy Madley,A

### Aditional Notes
This dataframe will hopefully be useful to make a machine learning model to predict match results, the different columns will act as variables and the result column could be used as a label.

In [70]:
#Export as csv
#will also leave the index since it does not have a default unique identifier, could use a multicolumn index though.
df.to_csv("matches_cleaned.csv")